name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
      - name: Install Node.js dependencies
        run: npm install
      - name: Move token files into /input
        run: |
          cp "tokens/light.json" "input/themes/light/light.json"
          cp "tokens/dark.json" "input/themes/dark/dark.json"
          cp "tokens/global.json" "input/globals/global.json"
          cp "tokens/compact.json" "input/globals/layout.json"
        shell: bash
      - name: Transform tokens with Style Dictionary
        run: npm run build
      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Automated token transformation triggered by new commit
